site_name: Everything In One Place
theme: 
    name: material
    palette: 
        # Palette toggle for dark mode
        - scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        # Palette toggle for light mode
        - scheme: default
          primary: red
          accent: red
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
    features:
      - content.code.copy
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - navigation.path
      - navigation.prune
      - navigation.indexes
      - navigation.top
      - toc.follow
extra_css:
  - stylesheets/extra.css   
    
    
