site_name: Everything In One Place
theme: 
    name: material
    palette: 
        # Palette toggle for dark mode
        - scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        # Palette toggle for light mode
        - scheme: default
          primary: red
          accent: red
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
    features:
        - content.code.copy
extra_css:
  - stylesheets/extra.css   
    
    
