site_name: Everything In One Place
theme: 
    name: material
    palette:
        scheme: slate
        primary: custom
        accent: red
    features:
        - content.code.copy
extra_css:
  - stylesheets/extra.css 
theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  
    
    
